version: "2"
services:
  clients-service:
    image: golang:1.14.7
    volumes:
      - ./clients-service:/go/src/clients-service
    working_dir: /go/src/clients-service
    command: go run main.go
    ports:
      - 0.0.0.0:10000:10000
  port-service:
    image: golang:1.14.7
    volumes:
      - ./port-service/:/go/src/port-service
    working_dir: /go/src/port-service
    command: go run main.go
    ports:
      - 0.0.0.0:10001:10001

#  TODO : add a database